チャット画面を実装しました。
Sumt32/chat-space pull request #2
Opened 2019-01-28 12:14 UTC by Sumt32

![Uploading Chat-space.png…]()

2019-01-28 12:36 UTC, ghost requested changes

2019-01-28 12:36 UTC, hiroki5123 commented on app/assets/stylesheets/_message.scss
> +  .left-container--top {
アンパサンド使いましょう

2019-01-28 12:36 UTC, hiroki5123 commented on app/assets/stylesheets/_message.scss
> +    padding: 20px 20px 20px 20px;
こちらは20px１つでいいと思います

2019-01-28 12:36 UTC, hiroki5123 commented on app/assets/stylesheets/_message.scss
> +    color: #FFFFFF;
よく使う色は変数化しましょう

2019-01-28 12:36 UTC, hiroki5123 commented on app/assets/stylesheets/_message.scss
> +      margin-top: 20px;
marginまとめてもいい気がします

2019-01-28 12:36 UTC, hiroki5123 commented on app/assets/stylesheets/_message.scss
> +}
最後に空行入れましょう

2019-01-28 12:36 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> +@import "./message";
最後に空行入れましょう

2019-01-28 12:36 UTC, hiroki5123 commented on app/views/messages/_side.html.haml
> +      %a.i.far.fa-edit{:href => "#"}
今のうちからlink_toで書いておくといいと思います

2019-01-28 12:36 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> += render :partial=>'side'
ハッシュロケット使わないようにしましょう

2019-01-28 12:51 UTC, Sumt32 commented on app/views/messages/index.html.haml
> += render :partial=>'side'
:に変換しました。

2019-01-28 13:30 UTC, Sumt32 commented on app/assets/stylesheets/_message.scss
> +    padding: 20px 20px 20px 20px;
padding: 20pxのみにしました。

2019-01-28 13:50 UTC, Sumt32 commented on app/assets/stylesheets/_message.scss
> +      margin-top: 20px;
marginまとめました

2019-01-28 13:51 UTC, Sumt32 commented on app/assets/stylesheets/_message.scss
> +}
空行入れました

2019-01-29 02:08 UTC, hzak2xx approved these changes
LGTMです

2019-01-29 02:53 UTC, merged